version: "3"

services:
  clients_dev:
    container_name: clients_dev
    image: clients_dev:1.0.0
    build:
      context: .
      target: develop
      dockerfile: ./Dockerfile
    command: yarn start:debug
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

